services:

  # CONTAO HOOKS:
  # Contao add parse template hook
  Markocupic\BackendPasswordRecoveryBundle\Listener\ContaoHooks\ParseTemplate:
    public: true
    arguments:
      - "@contao.framework"
      - "@request_stack"
      - "@twig"
      - "@translator"
      - "@uri_signer"
      - "@router"
      - '@contao.routing.scope_matcher'
    tags:
      - { name: contao.hook, hook: parseTemplate, method: addPasswordRecoveryLinkToContaoBackendLoginForm }
