services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      Symfony\Component\HttpKernel\UriSigner: '@uri_signer'

  Markocupic\BackendPasswordRecoveryBundle\:
    resource: ../../
    exclude: ../../{DependencyInjection,Resources}

  Markocupic\BackendPasswordRecoveryBundle\Subscriber\LoadAssets:
    tags:
      - { name: kernel.event_subscriber }
