services:

  Markocupic\BackendPasswordRecoveryBundle\Controller\BackendPasswordRecoveryController:
    public: true
    arguments:
      - '@uri_signer'
      - '@request_stack'

  Markocupic\BackendPasswordRecoveryBundle\Controller\RenewBackendPasswordController:
    public: true
    arguments:
      - '@contao.framework'
      - '@request_stack'
      - '@database_connection'
      - '@router'
      - '@Markocupic\BackendPasswordRecoveryBundle\InteractiveLogin\InteractiveBackendLogin'

  Markocupic\BackendPasswordRecoveryBundle\InteractiveLogin\InteractiveBackendLogin:
    public: true
    arguments:
      - '@contao.framework'
      - '@contao.security.user_checker'
      - '@session'
      - '@security.token_storage'
      - '@event_dispatcher'
      - '@request_stack'
      - '@monolog.logger.contao'
