services:

  Markocupic\BackendPasswordRecoveryBundle\Controller\PasswordRecoveryLinkRequestController:
    public: true
    arguments:
      - '@uri_signer'
      - '@request_stack'
      - '@router'
      - '@contao.csrf.token_manager'
      - '%contao.csrf_token_name%'

  Markocupic\BackendPasswordRecoveryBundle\Controller\RenewPasswordController:
    public: true
    arguments:
      - '@contao.framework'
      - '@request_stack'
      - '@database_connection'
      - '@router'
      - '@Markocupic\BackendPasswordRecoveryBundle\InteractiveLogin\InteractiveBackendLogin'
      - '@monolog.logger.contao'

  Markocupic\BackendPasswordRecoveryBundle\InteractiveLogin\InteractiveBackendLogin:
    public: true
    arguments:
      - '@contao.framework'
      - '@contao.security.user_checker'
      - '@session'
      - '@security.token_storage'
      - '@event_dispatcher'
      - '@request_stack'
      - '@monolog.logger.contao'
