services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $tokenLifetime: '%markocupic_backend_password_recovery.token_lifetime%'
      $showButtonOnLoginFailureOnly: '%markocupic_backend_password_recovery.show_button_on_login_failure_only%'

  Markocupic\BackendPasswordRecoveryBundle\:
    resource: ../src/
    exclude: ../src/{DependencyInjection}
