services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      Symfony\Component\HttpKernel\UriSigner: '@uri_signer'

  Markocupic\BackendPasswordRecoveryBundle\:
    resource: ../src/
    exclude: ../src/{DependencyInjection}

  Markocupic\BackendPasswordRecoveryBundle\Subscriber\LoadAssets:
    tags:
      - { name: kernel.event_subscriber }
