# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cs:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install ecs
        run: cd tools/ecs && composer install --no-interaction --no-suggest

      - name: Run the CS fixer
        run: composer cs-fixer

  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2 ]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install phpunit
        run: cd tools/phpunit && composer install --no-interaction --no-suggest

      - name: Install the dependencies
        run: composer install --no-interaction --no-suggest

      - name: Run the unit tests
        run: composer unit-tests

    prefer-lowest-tests:
      name: PHP ${{ matrix.php }} --prefer-lowest
      runs-on: ubuntu-latest
      if: github.event_name != 'push'
      strategy:
        fail-fast: false
        matrix:
          php: [ 8.1, 8.2 ]
      steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}

        - name: Checkout
          uses: actions/checkout@v2

        - name: Install phpunit
          run: cd tools/phpunit && composer install --no-interaction --no-suggest

        - name: Install the dependencies
          run: composer update --prefer-lowest --prefer-stable --no-interaction --no-suggest

        - name: Run the unit tests
          run: composer unit-tests